language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install: composer install
script: ./vendor/bin/phpunit

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
